#!/usr/bin/env ruby
# /usr/local/bin/vim-url-handle

require 'cgi'
require 'uri'

begin
  full_path = ARGV[0]
  exit unless full_path
  full_path = full_path.split('url=')[1].sub('&', '?') if full_path.include? 'url='

  uri = URI.parse(full_path)
  file = uri.path
  query = CGI.parse(uri.query)

  line = query['line'].first
  column = query['column'].first

  args = [file]
  args << line unless line.nil?
  args << column unless column.nil?
  exec "subl #{args.join(':')}"
rescue URI::InvalidURIError
end
